export const snackConstants = {
  SORT_BY_SEARCH: "SORT_BY_SEARCH",
  SORT_BY_ID: "SORT_BY_ID",
  SORT_BY_NAME: "SORT_BY_NAME",
  SORT_BY_WEIGHT: "SORT_BY_WEIGHT",
  SORT_BY_PRICE: "SORT_BY_PRICE",
  SORT_BY_CALORIES: "SORT_BY_CALORIES",
  SORT_BY_INGREDIENTS: "SORT_BY_INGREDIENTS",
};
